### PR TITLE
separate monitor function to three sub command

### PR DESCRIPTION
**Pull request by Solovyov1796**
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/26)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/26)* status: all files reviewed, 2 unresolved discussions (waiting on @0g-peterzhb and @Solovyov1796)

___
*[`cmd/root.go` line 56 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/26#-OEYT1AA6M28Lte1PPhT:-OEYT1AB4cQp6dWV6Of9:brhm8rg) ([raw file](https://github.com/0glabs/0g-monitor/blob/b885ae3f317754c4d4274461419358795c06ce99/cmd/root.go#L56)):*
> ```Go
> 
> // Execute is the command line entrypoint.
> func Execute() {
> ```

Why removed?
___
*[`cmd/root.go` line 23 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/26#-OEYTF1Z8PtvkOROD5vq:-OEYTF1Z8PtvkOROD5vr:bgsy9ce) ([raw file](https://github.com/0glabs/0g-monitor/blob/bab1a6c3f7a41837144ba40d6842e656125554b5/cmd/root.go#L23)):*
> ```Go
> 		Use:   "0g-monitor",
> 		Short: "Daemon to monitor all 0G service status",
> 		PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
> ```

Unnecessary?

**Comment by Solovyov1796** [comment]
*[`cmd/root.go` line 23 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/26#-OEYTF1Z8PtvkOROD5vq:-OEYVs_rCMzfwM18f9xD:b-hfpv0l) ([raw file](https://github.com/0glabs/0g-monitor/blob/bab1a6c3f7a41837144ba40d6842e656125554b5/cmd/root.go#L23)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Unnecessary?
</blockquote></details>

removed

**Comment by Solovyov1796** [comment]
*[`cmd/root.go` line 56 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/26#-OEYT1AA6M28Lte1PPhT:-OEYVwOO51Uff25mtS-5:b1zhm72) ([raw file](https://github.com/0glabs/0g-monitor/blob/b885ae3f317754c4d4274461419358795c06ce99/cmd/root.go#L56)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why removed?
</blockquote></details>

recovered

**Review by boqiu — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/26)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0g-peterzhb)

**Pull request merged**
