### PR TITLE
@peter/liveness monitor

### PR DESCRIPTION
**Pull request by 0g-peterzhb**
This change is [Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)

### CODE REVIEW

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: all files reviewed, 7 unresolved discussions (waiting on @0g-peterzhb)

___
*[`.gitignore` line 37 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSOejq8xBP4Nfx_GjJ:-NzSOejq8xBP4Nfx_GjK:b-b9zr62) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/.gitignore#L37)):*
> ```ignore
> *0g-storage-client
> *.csv
> metrics.json
> ```

Is it possible to avoid such temp files or folders?
___
*[`requirements.txt` line 1 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSMWJb0I9QSzoh4lJc:-NzSMWJb0I9QSzoh4lJd:bq7gwrt) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/requirements.txt#L1)):*
> ```help
> python-dotenv
> ```

Is it possible to use golang for all monitoring implementations?
___
*[`blockchain/serve.go` line 20 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSMzSyEttq2zwi6QfN:-NzSMzSyEttq2zwi6QfO:byt9hnd) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/serve.go#L20)):*
> ```Go
> 	ValidatorReport        health.TimedCounterConfig
> 	StorageNodes           map[string]string
> 	PrivateKey             string
> ```

Basically, I suggest to move storage nodes related monitoring items into separate package, e.g. `storage`.
___
*[`blockchain/storage_node.go` line 12 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNTqh7coqXKMKd2ss:-NzSNTqh7coqXKMKd2st:bfr5hxs) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L12)):*
> ```Go
> 
> const BlockRpcEndpoint = "https://rpc-testnet.0g.ai"
> const LogContract = "0xb8F03061969da6Ad38f0a4a9f8a86bE71dA3c8E7"
> ```

Not used?
___
*[`blockchain/storage_node.go` line 16 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNcVTE_s-2ytITlPf:-NzSNcVTE_s-2ytITlPg:b-3rpeid) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L16)):*
> ```Go
> 
> type StorageNode struct {
> 	client  jsonrpc.RPCClient
> ```

Why not use the storage node SDK `0g-storage-client`? Please refer to the `node` package.
___
*[`blockchain/storage_node.go` line 28 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNvj7-OTu9aHpxcf4:-NzSNvj7-OTu9aHpxcf5:b-pnapyp) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L28)):*
> ```Go
> 	}
> 
> 	return storageNode 
> ```

Could auto format the code to avoid the ending whitespace.
___
*[`blockchain/storage_node.go` line 57 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSOAUA-U1mHdVbcVDv:-NzSOAUA-U1mHdVbcVDw:b-4e35y0) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L57)):*
> ```Go
> func (node *StorageNode) CheckStatus(privateKey string, target uint64) {
>     
>     _, err := node.client.Call("zgs_getStatus")
> ```

Could follow the blockchain node to use `health` util instead, which tolerant errors in short time. Otherwise, the alert may be very noisy.

**Review by 0g-peterzhb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: 4 of 12 files reviewed, 7 unresolved discussions (waiting on @boqiu)

___
*[`.gitignore` line 37 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSOejq8xBP4Nfx_GjJ:-NzSfjaaEvPEeJRsM6Ni:b-d2lewm) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/.gitignore#L37)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to avoid such temp files or folders?
</blockquote></details>

they are not temp files actually.
___
*[`requirements.txt` line 1 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSMWJb0I9QSzoh4lJc:-NzSg-Ae4cCSaEMjQ2ah:bvbdplz) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/requirements.txt#L1)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Is it possible to use golang for all monitoring implementations?
</blockquote></details>

so far it may not be doable yet. 
___
*[`blockchain/serve.go` line 20 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSMzSyEttq2zwi6QfN:-NzSg2RC0rVimrWzJufJ:b-7rl0jd) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/serve.go#L20)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Basically, I suggest to move storage nodes related monitoring items into separate package, e.g. `storage`.
</blockquote></details>

done.
___
*[`blockchain/storage_node.go` line 12 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNTqh7coqXKMKd2ss:-NzSgGGr1YCS2ZbV6R9y:b-hfpv0l) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L12)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Not used?
</blockquote></details>

removed
___
*[`blockchain/storage_node.go` line 16 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNcVTE_s-2ytITlPf:-NzSm_EE10yMk42COWjz:bb7f2mf) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L16)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Why not use the storage node SDK `0g-storage-client`? Please refer to the `node` package.
</blockquote></details>

done
___
*[`blockchain/storage_node.go` line 28 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSNvj7-OTu9aHpxcf4:-NzSm_vGCRtHSiGZtUwT:bb7f2mf) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L28)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Could auto format the code to avoid the ending whitespace.
</blockquote></details>

done
___
*[`blockchain/storage_node.go` line 57 at r1](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzSOAUA-U1mHdVbcVDv:-NzSmd3Y5n8Qwo1-wBGk:b-896fix) ([raw file](https://github.com/0glabs/0g-monitor/blob/ec8d94b0ffcef094bfe0af97170fb4c28db30943/blockchain/storage_node.go#L57)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Could follow the blockchain node to use `health` util instead, which tolerant errors in short time. Otherwise, the alert may be very noisy.
</blockquote></details>

Done.

**Review by boqiu — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: all files reviewed, 4 unresolved discussions (waiting on @0g-peterzhb)

___
*[`blockchain/serve.go` line 19 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW3yh37HCc6E8-8uDV:-NzW3yh37HCc6E8-8uDW:b-hdyhn4) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/blockchain/serve.go#L19)):*
> ```Go
> 	Validators             map[string]string
> 	ValidatorReport        health.TimedCounterConfig
> 	PrivateKey             string
> ```

not used?
___
*[`cmd/root.go` line 34 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW4RXo-abOzbvkYy53:-NzW4RXo-abOzbvkYy54:b-iif9p0) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/cmd/root.go#L34)):*
> ```Go
> 
> 	startBlockchainAction(blockchain.MustMonitorFromViper, &wg)
> 	startStorageAction(storage.MustMonitorFromViper, &wg)
> ```

`startAction(storage.MustMonitorFromViper, &wg)`
___
*[`cmd/root.go` line 41 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW4BON7JLXiHypEX85:-NzW4BOO6mgy6tdDcOmo:b-u4d48i) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/cmd/root.go#L41)):*
> ```Go
> }
> 
> func startBlockchainAction(action func(), wg *sync.WaitGroup) {
> ```

Unnecessary to change the `startAction` method, which is used in common.
___
*[`storage/storage_node.go` line 46 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW597C0arvXOoRiZqN:-NzW597C0arvXOoRiZqO:b-hknrks) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/storage/storage_node.go#L46)):*
> ```Go
> }
> 
> func (node *StorageNode) CheckStatus(config health.TimedCounterConfig, privateKey string) {
> ```

Could remove such unused input parameter.

**Review by boqiu — COMMENTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: all files reviewed, 3 unresolved discussions (waiting on @0g-peterzhb)

**Review by boqiu — COMMENTED** [review]
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: all files reviewed, 2 unresolved discussions (waiting on @0g-peterzhb)

**Review by boqiu — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1#-:-O-FFNd35teYCl1Haaw5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @0g-peterzhb)

**Review by 0g-peterzhb — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @boqiu)

___
*[`cmd/root.go` line 34 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW4RXo-abOzbvkYy53:-O-FIKig5KoGa7QtvN9i:b-7ql1td) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/cmd/root.go#L34)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

`startAction(storage.MustMonitorFromViper, &wg)`
</blockquote></details>

fixed
___
*[`storage/storage_node.go` line 46 at r2](https://reviewable.io/reviews/0glabs/0g-monitor/1#-NzW597C0arvXOoRiZqN:-O-FHo_f7q_aDcBAzqrR:bdwbajr) ([raw file](https://github.com/0glabs/0g-monitor/blob/94a8c417d73c13c9ff2984f1f66df6230f74b1f8/storage/storage_node.go#L46)):*
<details><summary><i>Previously, boqiu (Bo QIU) wrote…</i></summary><blockquote>

Could remove such unused input parameter.
</blockquote></details>

 this is used I think.

**Review by boqiu — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/0glabs/0g-monitor/1)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @0g-peterzhb)

**Pull request merged**
